[project]
name = "bd3miner"
version = "1.0.0"
description = "Borderlands 3 Item/Object Class ID Scanner with file logging"
authors = [{name = "User"}]

[tool.sdkmod]
name = "bd3miner"
supported_games = ["BL3"]
